name: CI Checks

on: [push]

jobs:
  php-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name : Setup Config
      run:  composer config "http-basic.nova.laravel.com" "${{ secrets.NOVA_USERNAME }}" "${{ secrets.NOVA_PASSWORD }}"
    - name: Install depenedencies
      uses: php-actions/composer@v1
    - name: Run linter
      run: composer run lint

  npm-ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v3
    - name: Install depenedencies
      run: npm install
    - name: Run linter
      run: npm run lint
    - name: Build assets
      run: npm run prod
